### ISSUE TITLE
Command 'chs' not found

### ISSUE THREAD

**Issue by LittleTimmy63** [nickzuber/chs#16]
I am a Linux user. I was installed chs with pip and followed the install instructions. I typed "chs" (without the quotes) into the terminal, as was instructed, but the terminal states that there is no such command. How do I fix this? Can it be fixed?

**Comment by WilliamSchineider** [comment]
> I am a Linux user. I was installed chs with pip and followed the install instructions. I typed "chs" (without the quotes) into the terminal, as was instructed, but the terminal states that there is no such command. How do I fix this? Can it be fixed?

Hi LittleTimmy63, this issue may have happened because you have copied the following command `export PATH=”$PATH:$HOME/.local/bin”` without changing the "$HOME" part of the command. The correct version of this command is `export PATH="$PATH:/home/<THE-NAME-OF-YOUR-PC>/.local/bin"`, if you try it you will see that now when you type "chs" in your terminal it will run properly.

The solution above isn't the final solution, because when you use the `export PATH=”$PATH:$HOME/.local/bin”` it will work only at this session (until you close the current terminal), in order to add the folder permanently to the $PATH you should do the following:

1) Type `nano ~/.bashrc`, this command will open nano text editor.

2) Now add the the proper modified code `export PATH="$PATH:/home/<THE-NAME-OF-YOUR-PC>/.local/bin"` **at the end of the file**.

3) Press **ctrl + x**, then **y** to save the file.

Now, no matter where you are inside your Linux it will run the program if you type **chs** in your terminal!

I hope it solve your problem, best wishes!

**Comment by ghost** [comment]
> I am a Linux user. I was installed chs with pip and followed the install instructions. I typed "chs" (without the quotes) into the terminal, as was instructed, but the terminal states that there is no such command. How do I fix this? Can it be fixed?

Hi LittleTimmy63,

If you check your folder `/home/<YOUR-PC-NAME>/.local/bin`, you will see the **chs** listed, if not please uninstall the chs running the command `python3 -m pip uninstall chs`, then run again the `python3 -m pip install chs` command. Now I hope you will find it.

If you run the command `export PATH=”$PATH:$HOME/.local/bin”` you will be able to type **chs** anywhere on your linux and it will run the application properly, however this command will work only in the current session (until you close the terminal), to make it work permanently you need to add the folder `/home/<YOUR-PC-NAME>/.local/bin` to PATH.

For me it didn't work either, but if you have success with this method great, enjoy your terminal chess, if not try the following method:

Create an **alias** called **chs** by running the command `alias chs="/home/<YOUR-PC-NAME>/.local/bin/chs"`.

- If you have Fish Shell now run the command `funcsave chs`, the last command will make it work forever.
- If you use Bash then run `nano ~/.bash_aliases`, paste the alias you have created in this file, then **ctrl + x** and **y** to save. 

I hope it works for you as it did for me, best wishes!

**Comment by LittleTimmy63** [comment]
Thank you for the reply. I am sorry, but by the time you replied I had changed distros and I have no idea if your suggestion would have worked. Thank you.

**Comment by randomprsn47** [comment]
Thank you for explanation, i had the same problem first step didn't worked for me either the second did.
